// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiLTDA0KuVu-3_CZy4Kj8XSVcsL1seoMo',
    appId: '1:595917480413:web:5ece711e2e2ed7124b1634',
    messagingSenderId: '595917480413',
    projectId: 'schoolzap-aa207',
    authDomain: 'schoolzap-aa207.firebaseapp.com',
    storageBucket: 'schoolzap-aa207.firebasestorage.app',
    measurementId: 'G-TFPHBGTLJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqnfsSB7cFBoKXepXy31NQX0dLiO0Kz8',
    appId: '1:595917480413:android:8f65ab53426573164b1634',
    messagingSenderId: '595917480413',
    projectId: 'schoolzap-aa207',
    storageBucket: 'schoolzap-aa207.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrMo_4y7FxrP362JoUxvWOvT3WqqI_rLU',
    appId: '1:595917480413:ios:79da775a7fbf255b4b1634',
    messagingSenderId: '595917480413',
    projectId: 'schoolzap-aa207',
    storageBucket: 'schoolzap-aa207.firebasestorage.app',
    iosBundleId: 'com.example.schoolzap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrMo_4y7FxrP362JoUxvWOvT3WqqI_rLU',
    appId: '1:595917480413:ios:79da775a7fbf255b4b1634',
    messagingSenderId: '595917480413',
    projectId: 'schoolzap-aa207',
    storageBucket: 'schoolzap-aa207.firebasestorage.app',
    iosBundleId: 'com.example.schoolzap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiLTDA0KuVu-3_CZy4Kj8XSVcsL1seoMo',
    appId: '1:595917480413:web:7920b1d4f005660c4b1634',
    messagingSenderId: '595917480413',
    projectId: 'schoolzap-aa207',
    authDomain: 'schoolzap-aa207.firebaseapp.com',
    storageBucket: 'schoolzap-aa207.firebasestorage.app',
    measurementId: 'G-VCQXFEPQ32',
  );
}
